### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by AshAritra** [FalixNodes-Software/Mobile-App#2] opened 2022-01-12 03:23 UTC
In this app is quite good as i start but it's suck at loading page . Please fix this issue . And there is a problem with Google direct login .

**Comment by KorbsStudio** [comment] 2022-01-30 22:13
Google login is being fixed.

**Comment by KorbsStudio** [comment] 2022-02-28 03:14
Duplicate of #1

**Closed by KorbsStudio** 2022-02-28 03:14 UTC
Labels: duplicate
